import { TabItems } from './mocks';
export const accountOptions = [
  {
    option: 'Talent Signup',
    matIcon: 'build',
    route: '/talent/talent-signup',
    param: 'talent_onboarding',
  },
  {
    option: 'Scouter Signup',
    matIcon: 'credit_card',
    route: '/scouter/scouter-signup',
    param: 'scouter_onboarding',
  },
];
export const ImageStore = {
  backgroundImg: '/assets/images/oniduuru_bg.svg',
  openAcctImg: '/assets/images/oniduuru_openAcctPic.svg',
  shoftAfrica: '/assets/images/oniduuru_shoft_africa.svg',
  shoftAfricaBigLogo: '/assets/images/shoft_africa_noBackground.png',
  successIcon: '/assets/images/mark.svg',
  fileUploadIcon: '/assets/images/file_uploads.svg',
  verificationCompleted: '/assets/images/success.jpg',
  avatar: 'assets/images/avatar.png',
  sunrise: 'assets/images/sunrise.png',
  sunshine: 'assets/images/sunshine.png',
  sunset: 'assets/images/sunset.png',
  moonlight: 'assets/images/nights.png',
  graph: 'assets/images/graph.png',
  agreement: 'assets/images/agreement.png',
  accepted: 'assets/images/accepted.png',
  saving: 'assets/images/saving.png',
  reject: 'assets/images/reject.png',
  paymentVerification: 'assets/images/payment.png',
  pendingAcceptance: 'assets/images/clock.png',
  waiting: 'assets/images/waiting-list.png',
  noData: 'assets/images/404.png',
  imageUploads: 'assets/images/imageIcon.svg',
  reelIcon: 'assets/images/reel.svg',
  receipt: 'assets/images/receipt.png',
  uploadIcon: 'assets/images/uploadIcon.svg',
  picImage: 'assets/images/pictureImage.svg',
  skill: 'assets/images/skill.png',
  africaImg: 'assets/images/africa1.jpg',
  file: 'assets/images/file.svg',
  monitoBot: 'assets/images/monitor.jpg',
  verifyPayment: 'assets/images/verify.jpeg',
  scouterPayment: 'assets/images/payment1.jpeg',
  onboardingBot: 'assets/images/onboarding-hr.jpeg',
  profileBot: 'assets/images/scout.png',
  question: 'assets/images/question.png',
  deleteIcon: 'assets/images/delete.png',
  market:'assets/images/market.png',
  crowd:'assets/images/crowd.png',
  research:'assets/images/research.jpg',
  scouter: 'assets/images/scouter.png',
  marketImg:'assets/images/test1.png',
  marketImg2:'assets/images/test3.jpg',
  loggedInnUser: 'assets/images/loginn.jpg',
  skills: 'assets/images/skills.png',
  complaint:'assets/images/complaint3.jpg',
  complaint1:'assets/images/complaint_.jpg',
  scouterHire:'assets/images/hire1.jpg',
  handshake:'assets/images/handshake.png',
  notitifyUsers:'assets/images/notify2.png',
  fundDeposits:'assets/images/pension-plans.png',
  fundWithdrawal:'assets/images/withdraw.png',
  accountBalance:'assets/images/wallet.png',
  accountProfile:'assets/images/cash4.png',
  fundWallet:'assets/images/fund1.png', //cash1.jpg
  fundsWithdrawal: 'assets/images/withdrawal.png',
  fundsTransfer: 'assets/images/transfer.png',
  walletMetrics: 'assets/images/profit-metrics.png',
  walletStats: 'assets/images/stat.jpg',
  createWallet: 'assets/images/digi-wallet.jpg',
  allWallets: 'assets/images/deps.jpg',
  allDeposits: 'assets/images/all-wallets.jpg',
  allTransfers: 'assets/images/transfers.jpg',
  allWithdrawals: 'assets/images/withdrawals.jpg',
};


export const imageIcons = {
  scouterImage: '/assets/images/scouter.jpg',
  talentImage: '/assets/images/talent.png',
  ProfileIcon: '/assets/images/Profile-Icon.svg',
  NoDataImage: '/assets/images/NoDataImage.svg',
  LogComplaintModalBg: '/assets/images/Log-complaint-background.png',
  WELCOMEBGIMAGE: '/assets/images/WELCOMEBGIMAGE.svg',

  Morning: '/assets/icon/Morning.png',
  Afternoon: '/assets/icon/afternoon.png',
  Evening: '/assets/icon/Evening.png',
  Night: '/assets/icon/Night.png',
  UploadPayment: '/assets/icon/upload-payment.svg',
  VerifiedIconUpdateProfile: '/assets/icon/VerifiedIconUpdateProfile.svg',
  NotificationIcon: '/assets/icon/Notification-Icon.svg',
  ViewHireFolderIcon: '/assets/icon/view-hire-folder-icon.svg',
  FoxCryptoIcon: '/assets/icon/Fox-crypto-Icon.svg',
  WalletBalance: '/assets/icon/WalletBalance.svg',
  InfoIcon: '/assets/icon/Info-Icon.svg',
  TotalDeposit: '/assets/icon/TotalDeposit.svg',
  TotalWithdrawal: '/assets/icon/TotalWithdrawal.svg',
  TotalTransfer: '/assets/icon/TotalTransfer.svg',
  infoIcon: '/assets/icon/icon.png',
  logComplaintIcon: '/assets/icon/complaint.png',
  logoutIcon: '/assets/icon/logout.png',
  viewProfileIcon: '/assets/icon/profile.png',
  SkillSetIcon: '/assets/icon/SkillSetIcon.svg',
};

export const talentOnboardingTabItems: TabItems[] = [
  {
    path: 'talent-details',
    ionIcon: 'person-circle-outline',
    routerLink: '/talent/create-account/talent-details',
  },
  {
    path: 'talent-other-details',
    ionIcon: 'list-outline',
    routerLink: '/talent/create-account/talent-other-details',
  },
  {
    path: 'talent-login-credentials',
    ionIcon: 'key-outline',
    routerLink: '/talent/create-account/talent-login-credentials',
  },
  {
    path: 'talent-verify-credentials',
    ionIcon: 'shield-checkmark-outline',
    routerLink: '/talent/create-account/talent-verify-credentials',
  },
];

export const dummyLogin = [
  {
    email: 'scouter@oniduuru.com',
    password: 'scouter',
    role: 'scouter',
    route: '/scouter/dashboard',
  },
  {
    email: 'talent@oniduuru.com',
    password: 'talent',
    role: 'talent',
    route: '/talent/dashboard',
  },
];
